import NavbarPrivate from "@/components/ui/NavbarPrivate";
import AppSideBar from "@/components/controller/AppSideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Dashboardlayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSideBar />
      <main className="w-full ">
        <NavbarPrivate />
        {children}
      </main>
    </SidebarProvider>
  );
}
